/**
 * Generated by feeding the IMDb response JSON to https://transform.tools/json-to-typescript
 */

export interface IMDbDetailResponse {
	ok: boolean;
	error_code: number;
	imdbId: string;
	description: string;
	short: Short;
	top: Top;
	main: Main;
}

interface Short {
	'@context': string;
	'@type': string;
	'url': string;
	'name': string;
	'image': string;
	'description': string;
	'review': Review;
	'aggregateRating': AggregateRating;
	'contentRating': string;
	'genre': string[];
	'datePublished': string;
	'keywords': string;
	'trailer': Trailer;
	'actor': Actor[];
	'director': Director[];
	'creator': Creator[];
	'duration': string;
}

interface Review {
	'@type': string;
	'itemReviewed': ItemReviewed;
	'author': Author;
	'dateCreated': string;
	'inLanguage': string;
	'name': string;
	'reviewBody': string;
	'reviewRating': ReviewRating;
}

interface ItemReviewed {
	'@type': string;
	'url': string;
}

interface Author {
	'@type': string;
	'name': string;
}

interface ReviewRating {
	'@type': string;
	'worstRating': number;
	'bestRating': number;
	'ratingValue': number;
}

interface AggregateRating {
	'@type': string;
	'ratingCount': number;
	'bestRating': number;
	'worstRating': number;
	'ratingValue': number;
}

interface Trailer {
	'@type': string;
	'name': string;
	'embedUrl': string;
	'thumbnail': Thumbnail;
	'thumbnailUrl': string;
	'url': string;
	'description': string;
	'duration': string;
	'uploadDate': string;
}

interface Thumbnail {
	'@type': string;
	'contentUrl': string;
}

interface Actor {
	'@type': string;
	'url': string;
	'name': string;
}

interface Director {
	'@type': string;
	'url': string;
	'name': string;
}

interface Creator {
	'@type': string;
	'url': string;
	'name'?: string;
}

interface Top {
	id: string;
	productionStatus: ProductionStatus;
	canHaveEpisodes: boolean;
	titleText: TitleText;
	titleType: TitleType;
	originalTitleText: OriginalTitleText;
	certificate: Certificate;
	releaseYear: ReleaseYear;
	releaseDate: ReleaseDate;
	runtime: Runtime;
	canRate: CanRate;
	ratingsSummary: RatingsSummary;
	meterRanking: MeterRanking;
	primaryImage: PrimaryImage;
	images: Images;
	videos: Videos;
	primaryVideos: PrimaryVideos;
	externalLinks: ExternalLinks;
	metacritic: Metacritic;
	keywords: Keywords;
	isAdult: boolean;
	genres: Genres;
	interests: Interests;
	plot: Plot;
	plotContributionLink: PlotContributionLink;
	credits: Credits;
	principalCredits: PrincipalCredit[];
	reviews: Reviews;
	criticReviewsTotal: CriticReviewsTotal;
	triviaTotal: TriviaTotal;
	engagementStatistics: EngagementStatistics;
	subNavCredits: SubNavCredits;
	subNavReviews: SubNavReviews;
	subNavTrivia: SubNavTrivia;
	subNavFaqs: SubNavFaqs;
	subNavTopQuestions: SubNavTopQuestions;
	titleGenres: TitleGenres;
	meta: Meta;
	castPageTitle: CastPageTitle;
	directorsPageTitle: DirectorsPageTitle[];
	countriesOfOrigin: CountriesOfOrigin;
	production: Production;
	featuredReviews: FeaturedReviews;
	__typename: string;
}

interface ProductionStatus {
	currentProductionStage: CurrentProductionStage;
	productionStatusHistory: ProductionStatusHistory[];
	__typename: string;
}

interface CurrentProductionStage {
	id: string;
	text: string;
	__typename: string;
}

interface ProductionStatusHistory {
	status: Status;
	__typename: string;
}

interface Status {
	id: string;
	text: string;
	__typename: string;
}

interface TitleText {
	text: string;
	__typename: string;
}

interface TitleType {
	displayableProperty: DisplayableProperty;
	text: string;
	id: string;
	isSeries: boolean;
	isEpisode: boolean;
	categories: Category[];
	canHaveEpisodes: boolean;
	__typename: string;
}

interface DisplayableProperty {
	value: Value;
	__typename: string;
}

interface Value {
	plainText: string;
	__typename: string;
}

interface Category {
	value: string;
	__typename: string;
}

interface OriginalTitleText {
	text: string;
	__typename: string;
}

interface Certificate {
	rating: string;
	__typename: string;
}

interface ReleaseYear {
	year: number;
	endYear?: number;
	__typename: string;
}

interface ReleaseDate {
	day: number;
	month: number;
	year: number;
	__typename: string;
}

interface Runtime {
	seconds: number;
	displayableProperty: DisplayableProperty2;
	__typename: string;
}

interface DisplayableProperty2 {
	value: Value2;
	__typename: string;
}

interface Value2 {
	plainText: string;
	__typename: string;
}

interface CanRate {
	isRatable: boolean;
	__typename: string;
}

interface RatingsSummary {
	aggregateRating: number;
	voteCount: number;
	__typename: string;
}

interface MeterRanking {
	currentRank: number;
	rankChange: RankChange;
	__typename: string;
}

interface RankChange {
	changeDirection: string;
	difference: number;
	__typename: string;
}

interface PrimaryImage {
	id: string;
	width: number;
	height: number;
	url: string;
	caption: Caption;
	__typename: string;
}

interface Caption {
	plainText: string;
	__typename: string;
}

interface Images {
	total: number;
	edges: Edge[];
	__typename: string;
}

interface Edge {
	node: Node;
	__typename: string;
}

interface Node {
	id: string;
	__typename: string;
}

interface Videos {
	total: number;
	__typename: string;
}

interface PrimaryVideos {
	edges: Edge2[];
	__typename: string;
}

interface Edge2 {
	node: Node2;
	__typename: string;
}

interface Node2 {
	id: string;
	createdDate: string;
	isMature: boolean;
	runtime: Runtime2;
	name: Name;
	description: Description;
	timedTextTracks: TimedTextTrack[];
	recommendedTimedTextTrack?: RecommendedTimedTextTrack;
	thumbnail: Thumbnail2;
	primaryTitle: PrimaryTitle;
	playbackURLs: PlaybackUrl[];
	contentType: ContentType;
	previewURLs: PreviewUrl[];
	__typename: string;
}

interface Runtime2 {
	value: number;
	__typename: string;
}

interface Name {
	value: string;
	language: string;
	__typename: string;
}

interface Description {
	value: string;
	language: string;
	__typename: string;
}

interface TimedTextTrack {
	displayName: DisplayName;
	refTagFragment: string;
	type: string;
	language: string;
	url: string;
	__typename: string;
}

interface DisplayName {
	value: string;
	language: string;
	__typename: string;
}

interface RecommendedTimedTextTrack {
	displayName: DisplayName2;
	refTagFragment: string;
	type: string;
	language: string;
	url: string;
	__typename: string;
}

interface DisplayName2 {
	value: string;
	language: string;
	__typename: string;
}

interface Thumbnail2 {
	url: string;
	height: number;
	width: number;
	__typename: string;
}

interface PrimaryTitle {
	id: string;
	titleText: TitleText2;
	originalTitleText: OriginalTitleText2;
	releaseYear: ReleaseYear2;
	__typename: string;
}

interface TitleText2 {
	text: string;
	__typename: string;
}

interface OriginalTitleText2 {
	text: string;
	__typename: string;
}

interface ReleaseYear2 {
	year: number;
	__typename: string;
}

interface PlaybackUrl {
	displayName: DisplayName3;
	videoMimeType: string;
	videoDefinition: string;
	url: string;
	__typename: string;
}

interface DisplayName3 {
	value: string;
	language: string;
	__typename: string;
}

interface ContentType {
	id: string;
	displayName: DisplayName4;
	__typename: string;
}

interface DisplayName4 {
	value: string;
	__typename: string;
}

interface PreviewUrl {
	displayName: DisplayName5;
	videoMimeType: string;
	videoDefinition: string;
	url: string;
	__typename: string;
}

interface DisplayName5 {
	value: string;
	language: string;
	__typename: string;
}

interface ExternalLinks {
	total: number;
	__typename: string;
}

interface Metacritic {
	metascore: Metascore;
	__typename: string;
}

interface Metascore {
	score: number;
	__typename: string;
}

interface Keywords {
	total: number;
	edges: Edge3[];
	__typename: string;
}

interface Edge3 {
	node: Node3;
	__typename: string;
}

interface Node3 {
	text: string;
	__typename: string;
}

interface Genres {
	genres: Genre[];
	__typename: string;
}

interface Genre {
	text: string;
	id: string;
	__typename: string;
}

interface Interests {
	edges: Edge4[];
	__typename: string;
}

interface Edge4 {
	node: Node4;
	__typename: string;
}

interface Node4 {
	id: string;
	primaryText: PrimaryText;
	__typename: string;
}

interface PrimaryText {
	text: string;
	__typename: string;
}

interface Plot {
	plotText: PlotText;
	language: Language;
	__typename: string;
}

interface PlotText {
	plainText: string;
	__typename: string;
}

interface Language {
	id: string;
	__typename: string;
}

interface PlotContributionLink {
	url: string;
	__typename: string;
}

interface Credits {
	total: number;
	__typename: string;
}

interface PrincipalCredit {
	totalCredits: number;
	category: Category2;
	credits: Credit[];
	__typename: string;
}

interface Category2 {
	text: string;
	id: string;
	__typename: string;
}

interface Credit {
	name: Name2;
	__typename: string;
}

interface Name2 {
	nameText: NameText;
	id: string;
	__typename: string;
}

interface NameText {
	text: string;
	__typename: string;
}

interface Reviews {
	total: number;
	__typename: string;
}

interface CriticReviewsTotal {
	total: number;
	__typename: string;
}

interface TriviaTotal {
	total: number;
	__typename: string;
}

interface EngagementStatistics {
	watchlistStatistics: WatchlistStatistics;
	__typename: string;
}

interface WatchlistStatistics {
	displayableCount: DisplayableCount;
	__typename: string;
}

interface DisplayableCount {
	text: string;
	__typename: string;
}

interface SubNavCredits {
	total: number;
	__typename: string;
}

interface SubNavReviews {
	total: number;
	__typename: string;
}

interface SubNavTrivia {
	total: number;
	__typename: string;
}

interface SubNavFaqs {
	total: number;
	__typename: string;
}

interface SubNavTopQuestions {
	total: number;
	__typename: string;
}

interface TitleGenres {
	genres: Genre2[];
	__typename: string;
}

interface Genre2 {
	genre: Genre3;
	__typename: string;
}

interface Genre3 {
	text: string;
	__typename: string;
}

interface Meta {
	canonicalId: string;
	publicationStatus: string;
	__typename: string;
}

interface CastPageTitle {
	edges: Edge5[];
	__typename: string;
}

interface Edge5 {
	node: Node5;
	__typename: string;
}

interface Node5 {
	name: Name3;
	__typename: string;
}

interface Name3 {
	id: string;
	nameText: NameText2;
	__typename: string;
}

interface NameText2 {
	text: string;
	__typename: string;
}

interface DirectorsPageTitle {
	credits: Credit2[];
	__typename: string;
}

interface Credit2 {
	name: Name4;
	__typename: string;
}

interface Name4 {
	id: string;
	nameText: NameText3;
	__typename: string;
}

interface NameText3 {
	text: string;
	__typename: string;
}

interface CountriesOfOrigin {
	countries: Country[];
	__typename: string;
}

interface Country {
	id: string;
	__typename: string;
}

interface Production {
	edges: Edge6[];
	__typename: string;
}

interface Edge6 {
	node: Node6;
	__typename: string;
}

interface Node6 {
	company: Company;
	__typename: string;
}

interface Company {
	id: string;
	companyText: CompanyText;
	__typename: string;
}

interface CompanyText {
	text: string;
	__typename: string;
}

interface FeaturedReviews {
	edges: Edge7[];
	__typename: string;
}

interface Edge7 {
	node: Node7;
	__typename: string;
}

interface Node7 {
	author: Author2;
	summary: Summary;
	text: Text;
	authorRating: number;
	submissionDate: string;
	__typename: string;
}

interface Author2 {
	nickName: string;
	__typename: string;
}

interface Summary {
	originalText: string;
	__typename: string;
}

interface Text {
	originalText: OriginalText;
	__typename: string;
}

interface OriginalText {
	plainText: string;
	__typename: string;
}

interface Main {
	id: string;
	wins: Wins;
	nominationsExcludeWins: NominationsExcludeWins;
	prestigiousAwardSummary: PrestigiousAwardSummary;
	ratingsSummary: RatingsSummary2;
	videos: Videos2;
	videoStrip: VideoStrip;
	titleMainImages: TitleMainImages;
	productionStatus: ProductionStatus2;
	primaryImage: PrimaryImage2;
	inIframeAddLink: InIframeAddLink;
	notInIframeAddLink: NotInIframeAddLink;
	titleType: TitleType2;
	cast: Cast;
	directors: Director2[];
	writers: Writer[];
	isAdult: boolean;
	moreLikeThisTitles: MoreLikeThisTitles;
	triviaTotal: TriviaTotal2;
	trivia: Trivia;
	goofsTotal: GoofsTotal;
	goofs: Goofs;
	quotesTotal: QuotesTotal;
	quotes: Quotes;
	crazyCredits: CrazyCredits;
	alternateVersions: AlternateVersions;
	connections: Connections;
	soundtrack: Soundtrack;
	titleText: TitleText6;
	originalTitleText: OriginalTitleText6;
	releaseYear: ReleaseYear5;
	reviews: Reviews2;
	featuredReviews: FeaturedReviews2;
	canRate: CanRate3;
	iframeAddReviewLink: IframeAddReviewLink;
	topQuestions: TopQuestions;
	faqs: Faqs;
	releaseDate: ReleaseDate2;
	countriesOfOrigin: CountriesOfOrigin2;
	detailsExternalLinks: DetailsExternalLinks;
	spokenLanguages: SpokenLanguages;
	akas: Akas;
	filmingLocations: FilmingLocations;
	production: Production2;
	companies: Companies;
	productionBudget: ProductionBudget;
	lifetimeGross: LifetimeGross;
	openingWeekendGross: OpeningWeekendGross;
	worldwideGross: WorldwideGross;
	technicalSpecifications: TechnicalSpecifications;
	runtime: Runtime5;
	canHaveEpisodes: boolean;
	contributionQuestions: ContributionQuestions;
	__typename: string;
}

interface Wins {
	total: number;
	__typename: string;
}

interface NominationsExcludeWins {
	total: number;
	__typename: string;
}

interface PrestigiousAwardSummary {
	nominations: number;
	wins: number;
	award: Award;
	__typename: string;
}

interface Award {
	text: string;
	id: string;
	event: Event;
	__typename: string;
}

interface Event {
	id: string;
	__typename: string;
}

interface RatingsSummary2 {
	topRanking: TopRanking;
	__typename: string;
}

interface TopRanking {
	id: string;
	text: Text2;
	rank: number;
	__typename: string;
}

interface Text2 {
	value: string;
	__typename: string;
}

interface Videos2 {
	total: number;
	__typename: string;
}

interface VideoStrip {
	edges: Edge8[];
	__typename: string;
}

interface Edge8 {
	node: Node8;
	__typename: string;
}

interface Node8 {
	id: string;
	contentType: ContentType2;
	name: Name5;
	runtime: Runtime3;
	thumbnail: Thumbnail3;
	__typename: string;
}

interface ContentType2 {
	displayName: DisplayName6;
	__typename: string;
}

interface DisplayName6 {
	value: string;
	__typename: string;
}

interface Name5 {
	value: string;
	__typename: string;
}

interface Runtime3 {
	value: number;
	__typename: string;
}

interface Thumbnail3 {
	height: number;
	url: string;
	width: number;
	__typename: string;
}

interface TitleMainImages {
	total: number;
	edges: Edge9[];
	__typename: string;
}

interface Edge9 {
	node: Node9;
	__typename: string;
}

interface Node9 {
	id: string;
	url: string;
	caption: Caption2;
	height: number;
	width: number;
	__typename: string;
}

interface Caption2 {
	plainText: string;
	__typename: string;
}

interface ProductionStatus2 {
	currentProductionStage: CurrentProductionStage2;
	productionStatusHistory: ProductionStatusHistory2[];
	__typename: string;
}

interface CurrentProductionStage2 {
	id: string;
	text: string;
	__typename: string;
}

interface ProductionStatusHistory2 {
	status: Status2;
	__typename: string;
}

interface Status2 {
	id: string;
	text: string;
	__typename: string;
}

interface PrimaryImage2 {
	id: string;
	__typename: string;
}

interface InIframeAddLink {
	url: string;
	__typename: string;
}

interface NotInIframeAddLink {
	url: string;
	__typename: string;
}

interface TitleType2 {
	id: string;
	canHaveEpisodes: boolean;
	__typename: string;
}

interface Cast {
	total: number;
	edges: Edge10[];
	__typename: string;
}

interface Edge10 {
	node: Node10;
	__typename: string;
}

interface Node10 {
	name: Name6;
	category: Category3;
	characters: Character[];
	episodeCredits: EpisodeCredits;
	__typename: string;
}

interface Name6 {
	id: string;
	nameText: NameText4;
	primaryImage?: PrimaryImage3;
	__typename: string;
}

interface NameText4 {
	text: string;
	__typename: string;
}

interface PrimaryImage3 {
	url: string;
	width: number;
	height: number;
	__typename: string;
}

interface Category3 {
	id: string;
	__typename: string;
}

interface Character {
	name: string;
	__typename: string;
}

interface EpisodeCredits {
	total: number;
	__typename: string;
}

interface Director2 {
	totalCredits: number;
	category: Category4;
	credits: Credit3[];
	__typename: string;
}

interface Category4 {
	text: string;
	id: string;
	__typename: string;
}

interface Credit3 {
	name: Name7;
	__typename: string;
}

interface Name7 {
	id: string;
	nameText: NameText5;
	__typename: string;
}

interface NameText5 {
	text: string;
	__typename: string;
}

interface Writer {
	totalCredits: number;
	category: Category5;
	credits: Credit4[];
	__typename: string;
}

interface Category5 {
	text: string;
	id: string;
	__typename: string;
}

interface Credit4 {
	name: Name8;
	__typename: string;
}

interface Name8 {
	id: string;
	nameText: NameText6;
	__typename: string;
}

interface NameText6 {
	text: string;
	__typename: string;
}

interface MoreLikeThisTitles {
	edges: Edge11[];
	__typename: string;
}

interface Edge11 {
	node: Node11;
	__typename: string;
}

interface Node11 {
	id: string;
	titleText: TitleText3;
	titleType: TitleType3;
	originalTitleText: OriginalTitleText3;
	primaryImage: PrimaryImage4;
	releaseYear: ReleaseYear3;
	ratingsSummary: RatingsSummary3;
	runtime: Runtime4;
	certificate: Certificate2;
	canRate: CanRate2;
	titleGenres: TitleGenres2;
	canHaveEpisodes: boolean;
	__typename: string;
}

interface TitleText3 {
	text: string;
	__typename: string;
}

interface TitleType3 {
	id: string;
	text: string;
	canHaveEpisodes: boolean;
	displayableProperty: DisplayableProperty3;
	__typename: string;
}

interface DisplayableProperty3 {
	value: Value3;
	__typename: string;
}

interface Value3 {
	plainText: string;
	__typename: string;
}

interface OriginalTitleText3 {
	text: string;
	__typename: string;
}

interface PrimaryImage4 {
	id: string;
	width: number;
	height: number;
	url: string;
	caption: Caption3;
	__typename: string;
}

interface Caption3 {
	plainText: string;
	__typename: string;
}

interface ReleaseYear3 {
	year: number;
	endYear?: number;
	__typename: string;
}

interface RatingsSummary3 {
	aggregateRating: number;
	voteCount: number;
	__typename: string;
}

interface Runtime4 {
	seconds: number;
	__typename: string;
}

interface Certificate2 {
	rating: string;
	__typename: string;
}

interface CanRate2 {
	isRatable: boolean;
	__typename: string;
}

interface TitleGenres2 {
	genres: Genre4[];
	__typename: string;
}

interface Genre4 {
	genre: Genre5;
	__typename: string;
}

interface Genre5 {
	text: string;
	__typename: string;
}

interface TriviaTotal2 {
	total: number;
	__typename: string;
}

interface Trivia {
	edges: Edge12[];
	__typename: string;
}

interface Edge12 {
	node: Node12;
	__typename: string;
}

interface Node12 {
	text: Text3;
	trademark?: string;
	relatedNames?: string;
	__typename: string;
}

interface Text3 {
	plaidHtml: string;
	__typename: string;
}

interface GoofsTotal {
	total: number;
	__typename: string;
}

interface Goofs {
	edges: Edge13[];
	__typename: string;
}

interface Edge13 {
	node: Node13;
	__typename: string;
}

interface Node13 {
	text: Text4;
	__typename: string;
}

interface Text4 {
	plaidHtml: string;
	__typename: string;
}

interface QuotesTotal {
	total: number;
	__typename: string;
}

interface Quotes {
	edges: Edge14[];
	__typename: string;
}

interface Edge14 {
	node: Node14;
	__typename: string;
}

interface Node14 {
	lines: Line[];
	__typename: string;
}

interface Line {
	characters: Character2[];
	text: string;
	stageDirection: string;
	__typename: string;
}

interface Character2 {
	character: string;
	name: Name9;
	__typename: string;
}

interface Name9 {
	id: string;
	__typename: string;
}

interface CrazyCredits {
	edges: Edge15[];
	__typename: string;
}

interface Edge15 {
	node: Node15;
	__typename: string;
}

interface Node15 {
	text: Text5;
	__typename: string;
}

interface Text5 {
	plaidHtml: string;
	__typename: string;
}

interface AlternateVersions {
	total: number;
	edges: Edge16[];
	__typename: string;
}

interface Edge16 {
	node: Node16;
	__typename: string;
}

interface Node16 {
	text: Text6;
	__typename: string;
}

interface Text6 {
	plaidHtml: string;
	__typename: string;
}

interface Connections {
	edges: Edge17[];
	__typename: string;
}

interface Edge17 {
	node: Node17;
	__typename: string;
}

interface Node17 {
	associatedTitle: AssociatedTitle;
	category: Category6;
	__typename: string;
}

interface AssociatedTitle {
	id: string;
	releaseYear: ReleaseYear4;
	titleText: TitleText4;
	originalTitleText: OriginalTitleText4;
	series: Series;
	__typename: string;
}

interface ReleaseYear4 {
	year: number;
	__typename: string;
}

interface TitleText4 {
	text: string;
	__typename: string;
}

interface OriginalTitleText4 {
	text: string;
	__typename: string;
}

interface Series {
	series: Series2;
	__typename: string;
}

interface Series2 {
	titleText: TitleText5;
	originalTitleText: OriginalTitleText5;
	__typename: string;
}

interface TitleText5 {
	text: string;
	__typename: string;
}

interface OriginalTitleText5 {
	text: string;
	__typename: string;
}

interface Category6 {
	text: string;
	__typename: string;
}

interface Soundtrack {
	edges: Edge18[];
	__typename: string;
}

interface Edge18 {
	node: Node18;
	__typename: string;
}

interface Node18 {
	text: string;
	comments: Comment[];
	__typename: string;
}

interface Comment {
	plaidHtml: string;
	__typename: string;
}

interface TitleText6 {
	text: string;
	__typename: string;
}

interface OriginalTitleText6 {
	text: string;
	__typename: string;
}

interface ReleaseYear5 {
	year: number;
	__typename: string;
}

interface Reviews2 {
	total: number;
	__typename: string;
}

interface FeaturedReviews2 {
	edges: Edge19[];
	__typename: string;
}

interface Edge19 {
	node: Node19;
	__typename: string;
}

interface Node19 {
	id: string;
	author: Author3;
	summary: Summary2;
	text: Text7;
	authorRating: number;
	submissionDate: string;
	helpfulness: Helpfulness;
	__typename: string;
}

interface Author3 {
	nickName: string;
	userId: string;
	__typename: string;
}

interface Summary2 {
	originalText: string;
	__typename: string;
}

interface Text7 {
	originalText: OriginalText2;
	__typename: string;
}

interface OriginalText2 {
	plaidHtml: string;
	__typename: string;
}

interface Helpfulness {
	upVotes: number;
	downVotes: number;
	__typename: string;
}

interface CanRate3 {
	isRatable: boolean;
	__typename: string;
}

interface IframeAddReviewLink {
	url: string;
	__typename: string;
}

interface TopQuestions {
	total: number;
	edges: Edge20[];
	__typename: string;
}

interface Edge20 {
	node: Node20;
	__typename: string;
}

interface Node20 {
	attributeId: string;
	question: Question;
	__typename: string;
}

interface Question {
	plainText: string;
	__typename: string;
}

interface Faqs {
	total: number;
	edges: Edge21[];
	__typename: string;
}

interface Edge21 {
	node: Node21;
	__typename: string;
}

interface Node21 {
	id: string;
	question: Question2;
	__typename: string;
}

interface Question2 {
	plainText: string;
	__typename: string;
}

interface ReleaseDate2 {
	day: number;
	month: number;
	year: number;
	country: Country2;
	__typename: string;
}

interface Country2 {
	id: string;
	text: string;
	__typename: string;
}

interface CountriesOfOrigin2 {
	countries: Country3[];
	__typename: string;
}

interface Country3 {
	id: string;
	text: string;
	__typename: string;
}

interface DetailsExternalLinks {
	edges: Edge22[];
	total: number;
	__typename: string;
}

interface Edge22 {
	node: Node22;
	__typename: string;
}

interface Node22 {
	url: string;
	label: string;
	externalLinkRegion?: ExternalLinkRegion;
	__typename: string;
}

interface ExternalLinkRegion {
	text: string;
	__typename: string;
}

interface SpokenLanguages {
	spokenLanguages: SpokenLanguage[];
	__typename: string;
}

interface SpokenLanguage {
	id: string;
	text: string;
	__typename: string;
}

interface Akas {
	edges: Edge23[];
	__typename: string;
}

interface Edge23 {
	node: Node23;
	__typename: string;
}

interface Node23 {
	text: string;
	__typename: string;
}

interface FilmingLocations {
	edges: Edge24[];
	total: number;
	__typename: string;
}

interface Edge24 {
	node: Node24;
	__typename: string;
}

interface Node24 {
	text: string;
	location: string;
	attributes: Attribute[];
	__typename: string;
}

interface Attribute {
	text: string;
	__typename: string;
}

interface Production2 {
	edges: Edge25[];
	__typename: string;
}

interface Edge25 {
	node: Node25;
	__typename: string;
}

interface Node25 {
	company: Company2;
	__typename: string;
}

interface Company2 {
	id: string;
	companyText: CompanyText2;
	__typename: string;
}

interface CompanyText2 {
	text: string;
	__typename: string;
}

interface Companies {
	total: number;
	__typename: string;
}

interface ProductionBudget {
	budget: Budget;
	__typename: string;
}

interface Budget {
	amount: number;
	currency: string;
	__typename: string;
}

interface LifetimeGross {
	total: Total;
	__typename: string;
}

interface Total {
	amount: number;
	currency: string;
	__typename: string;
}

interface OpeningWeekendGross {
	gross: Gross;
	weekendEndDate: string;
	__typename: string;
}

interface Gross {
	total: Total2;
	__typename: string;
}

interface Total2 {
	amount: number;
	currency: string;
	__typename: string;
}

interface WorldwideGross {
	total: Total3;
	__typename: string;
}

interface Total3 {
	amount: number;
	currency: string;
	__typename: string;
}

interface TechnicalSpecifications {
	soundMixes: SoundMixes;
	aspectRatios: AspectRatios;
	colorations: Colorations;
	__typename: string;
}

interface SoundMixes {
	items: Item[];
	__typename: string;
}

interface Item {
	id: string;
	text: string;
	__typename: string;
}

interface AspectRatios {
	items: Item2[];
	__typename: string;
}

interface Item2 {
	aspectRatio: string;
	__typename: string;
}

interface Colorations {
	__typename: string;
}

interface Runtime5 {
	seconds: number;
	__typename: string;
}

interface ContributionQuestions {
	contributionLink: ContributionLink;
	__typename: string;
}

interface ContributionLink {
	url: string;
	__typename: string;
}
