/**
 * Generated by feeding the IMDb response JSON to https://transform.tools/json-to-typescript
 */

export interface IMDbSearchResponse {
	ok: boolean;
	error_code: number;
	description: Description[];
}

type Description = {
	'#IMDB_ID': string;
	'#TITLE': string;
	'#YEAR'?: number;
	'#RANK': number;
	'#ACTORS': string;
	'#AKA': string;
	'#IMDB_URL': string;
	'#IMDB_IV': string;
	'#IMG_POSTER'?: string;
	'photo_width'?: number;
	'photo_height'?: number;
};
